#!/bin/bash

sname=("BK" "BL" "RE" "MA" "GR" "CY" "YL" "WH")
snameL=("Bk" "Bl" "Re" "Ma" "Gr" "Cy" "Yl" "Wh")
lname=("BLACK" "BLUE" "RED" "MAGENTA" "GREEN" "CYAN" "YELLOW" "WHITE")

echo ";"
echo "; Autogenerated ink/paper color combo names"
echo ";"

for i in {0..7}; do
 for j in {0..7}; do
  color="${lname[j]}+${lname[i]}*8"
  if [ ${#color} -lt 12 ]; then
    tabs="\t\t"
  else
    tabs="\t"
  fi
  echo -e "${sname[j]}${sname[i]}\tEQU $color$tabs; ${lname[j]} ink on ${lname[i]} background"
 done
done

echo ""

for i in {0..7}; do
 for j in {0..7}; do
  color="64+${lname[j]}+${lname[i]}*8"
  if [ ${#color} -lt 11 ]; then
    tabs="\t\t"
  else
    tabs="\t"
  fi
  echo -e "${snameL[j]}${sname[i]}\tEQU $color$tabs; Bright ${lname[j]} ink on ${lname[i]} background"
 done
done

echo ""