TARGET  = gorgon

PASMO	= pasmo6
PASMOFLAGS = --tapbas --listing gorgon.lst

EMU	= fuse
#EMUFLAGS= --late-timings --graphics-filter advmame2x --no-confirm-action
EMUFLAGS= --late-timings --graphics-filter 2x --no-confirm-action

INCLUDES = \
	macros.asm \
	key.asm \
	ground.asm \
	score.asm \
	ship.asm \
	ytable.asm \
	fatfont.asm \
	shipdata.inc \
	grounddata.inc \
	groundmapdata.inc \
	colors.inc

.PHONY : all run assets clean fullclean

all : clean $(TARGET).tap run

$(TARGET).tap : gorgon.asm $(INCLUDES)
	@echo "[assembling to .tap"]
	@$(PASMO) $(PASMOFLAGS) $< $@

run :
	@$(EMU) $(EMUFLAGS) $(TARGET).tap 2> /dev/null

shipdata.inc : assets/shipR.txt assets/shipL.txt
	@echo "[spriting ships]"
	@rm -f $@
	@echo ";" >> $@
	@echo "; Autogenerated by spriter.sh" >> $@
	@echo ";" >> $@
	@spriteMaker/spriter.sh assets/shipR.txt shipR reverse >> $@
	@echo "       DS 32 ; Filler" >> $@
	@spriteMaker/spriter.sh assets/shipL.txt shipL reverse > /tmp/tmp.tmp
	@cat /tmp/tmp.tmp | grep LUT >> $@
	@cat /tmp/tmp.tmp | grep -v LUT >> $@
	@echo "" >> $@
	@echo " IF shipL0 - shipR0 != 256" >> $@
	@echo "   .ERROR ShipL0 and shipR0 must be $100 bytes apart" >> $@
	@echo " ENDIF" >> $@
	

colors.inc :
	@echo "[creating colors]"
	@./createColorNames.sh > $@

grounddata.inc :
	@echo "[creating ground]"
	@createGround/process.sh assets/grounddata.txt > $@

groundmapdata.inc :
	@echo "[creating groundmap]"
	@createGround/makemap.sh assets/groundmapdata.txt GroundMap > $@

fullclean : clean
	@rm -f *.inc

clean :
	@rm -rf *.tap *.tmp *.bin *.lst
	@rm -f *~ */*~
	
